title: O365 Home Assistant
remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 3

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/RogerSelwyn/O365-HomeAssistant" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

footer_content: "To learn about migration to the new MS365 integrations click here - <a href=\"https://rogerselwyn.github.io/O365-HomeAssistant/migration\">Migration</a>"